---
title: "code"
author: "VARSHA JAKNAMPALLY"
date: "2026-05-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# 1. Load Required Libraries
library(ggplot2)
library(lubridate)
library(corrplot)
```

```{r}
# 2. Load Dataset

data <- readRDS("data/Nivolet.rds")
```

```{r}
# 3. Initial Dataset Inspection
dim(data)
names(data)
str(data)
summary(data)
```


```{r}
# 4. Data Quality Assessment
# ---- Missing Values ----
colSums(is.na(data))
round(colMeans(is.na(data)) * 100, 2)
# ---- Infinite Values ----
sapply(data, function(x) sum(is.infinite(x)))
# ---- Duplicate Timestamps ----
sum(duplicated(data$timestamp))
# ---- Temporal Consistency Check ----
time_diff <- diff(data$timestamp)
table(time_diff)
```

```{r}
# 5. Exploratory Data Analysis
hist(data$net_ecosystem_exchange)

hist(data$air_temperature)

hist(data$incoming_shortwave_radiation)

# ---- Boxplots for Outlier Detection ----

boxplot(data$net_ecosystem_exchange)

boxplot(data$latent_heat_flux)

boxplot(data$sensible_heat_flux)

```

```{r}
# 6. Correlation Analysis
numeric_data <- data[sapply(data, is.numeric)]

cor_matrix <- cor(numeric_data)

round(cor_matrix, 2)
```


```{r}
# 7. Time-Based Feature Engineering

data$year  <- year(data$timestamp)
data$month <- month(data$timestamp)
data$hour  <- hour(data$timestamp)
```

```{r}
# 8. Time-Series Visualisation
# ---- Net Ecosystem Exchange Over Time ----
ggplot(data,
       aes(x = timestamp,
           y = net_ecosystem_exchange)) +
  geom_line(alpha = 0.4)

ggsave(
  "plots/plot_02_nee_timeseries.png",
  width = 10,
  height = 5,
  dpi = 300
)
```

```{r}
# ---- Monthly Seasonal Patterns ----
ggplot(data,
       aes(x = factor(month),
           y = net_ecosystem_exchange)) +
  geom_boxplot()
```

```{r}
# ---- Radiation vs NEE Relationship ----
ggplot(data,
       aes(x = incoming_shortwave_radiation,
           y = net_ecosystem_exchange)) +
  geom_point(alpha = 0.1)
```


```{r}
# 9. Baseline Linear Regression Model
model_lm <- lm(
  net_ecosystem_exchange ~
    incoming_shortwave_radiation +
    latent_heat_flux +
    sensible_heat_flux +
    air_temperature,
  data = data
)

# ---- Model Summary ----
summary(model_lm)
```


